#!/usr/bin/env bash
VMS=(k3s-ctrl k3s-work)
VM_RAM=1G
VM_DISK=5G

if [[ $1 == '--clean' ]]; then
    echo "====> Performing a clean install"
    multipass delete --all
    multipass purge
fi

for VM in ${VMS[*]}; do
    echo "====> ${VM}: Installing VM"
    multipass launch --name ${VM} --mem ${VM_RAM} --disk ${VM_DISK}

    echo "====> ${VM}: Updating applications"
    multipass exec ${VM} -- sh -c "sudo apt update && sudo DEBIAN_FRONTEND=noninteractive apt upgrade -y"

    if [ -z "${K3S_URL}" ]; then
        echo "====> ${VM}: Installing k3s (controller)"
        multipass exec ${VM} -- sh -c "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--write-kubeconfig=/home/ubuntu/.kube/config --write-kubeconfig-mode=644' sh -"

        echo "====> ${VM}: Getting controller details"
        K3S_URL='https://'$(multipass exec ${VM} -- hostname -I | awk '{print $1}')':6443'
        K3S_TOKEN=$(multipass exec ${VM} -- sudo cat /var/lib/rancher/k3s/server/node-token)
        echo "${VM}: ${K3S_URL} ${K3S_TOKEN}"
    else
        echo "====> ${VM}: Installing k3s (worker)"
        multipass exec ${VM} -- sh -c "curl -sfL https://get.k3s.io | K3S_URL=${K3S_URL} K3S_TOKEN=${K3S_TOKEN} sh -"
        multipass exec ${VM} -- sudo systemctl enable --now k3s-agent
    fi

    echo
    echo
done
